= Office Commute API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[overview]]
== Overview

사내 출퇴근 관리 시스템 API 문서입니다.

[[api-employee]]
== Employee API

[[api-employee-save]]
=== 직원 등록

operation::employee-save[snippets='http-request,request-fields,http-response']

[[api-employee-find-all]]
=== 직원 전체 조회

operation::employee-find-all[snippets='http-request,http-response,response-fields']

[[api-employee-update-team]]
=== 직원 팀 변경

operation::employee-update-team[snippets='http-request,request-fields,http-response']

[[api-team]]
== Team API

[[api-team-register]]
=== 팀 등록

operation::team-register[snippets='http-request,request-fields,http-response']

[[api-team-find-all]]
=== 팀 전체 조회

operation::team-find-all[snippets='http-request,http-response,response-fields']

[[api-commute]]
== Commute API

[[api-commute-start]]
=== 출근 등록

operation::commute-start[snippets='http-request,http-response']

[[api-commute-end]]
=== 퇴근 등록

operation::commute-end[snippets='http-request,http-response']

[[api-commute-duration]]
=== 월별 근무시간 조회

operation::commute-duration[snippets='http-request,query-parameters,http-response,response-fields']

[[api-annual-leave]]
== Annual Leave API

[[api-annual-leave-enroll]]
=== 연차 신청

operation::annual-leave-enroll[snippets='http-request,request-fields,http-response,response-fields']

[[api-annual-leave-remaining]]
=== 남은 연차 조회

operation::annual-leave-remaining[snippets='http-request,http-response,response-fields']

[[api-overtime]]
== Overtime API

[[api-overtime-calculate]]
=== 초과근무 조회

operation::overtime-calculate[snippets='http-request,query-parameters,http-response,response-fields']

NOTE: 초과근무 엑셀 리포트 다운로드는 `GET /overtime/report/excel?yearMonth=yyyy-MM` 로 요청합니다.
