/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 성공 시 새 HTTP 세션을 생성하고 `currentEmployeeId`, `currentRole`을 저장한다.
         *     기존 세션은 무효화된다(session fixation 방어).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 로그인 성공. 응답 본문 없음. Set-Cookie로 JSESSIONID 발급. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                /** @description 이메일 미존재 또는 비밀번호 불일치 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 로그인한 사용자 조회
         * @description 세션에 저장된 `currentEmployeeId`로 현재 사용자를 조회한다.
         *     SPA 부팅 시 로그인 상태 복원 및 역할 기반 화면 분기에 사용한다.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 현재 세션을 무효화한다. 세션이 없어도 200으로 처리한다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 로그아웃 처리됨. 응답 본문 없음. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 전체 조회
         * @description `memberCount`는 저장된 카운터가 아니라 `employee.team_id`의 COUNT 결과를 응답 시점에 합성한 값이다.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 팀 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamFindResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 팀 등록 (Manager Only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamRegisterRequest"];
                };
            };
            responses: {
                /** @description 등록 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamRegisterResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 동일 이름의 팀이 이미 존재 (TEAM_ALREADY_EXISTS) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 직원 전체 조회 (Manager Only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 직원 목록. 미배정 직원은 `teamId`/`teamName`이 null. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeFindResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * 직원 등록 (Manager Only)
         * @description `teamId`는 옵셔널. 없으면 미배정 직원으로 저장.
         *     `password`는 BCrypt로 인코딩되어 저장된다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeSaveRequest"];
                };
            };
            responses: {
                /** @description 등록 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeRegisterResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description teamId가 존재하지 않음 (TEAM_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description employeeCode 또는 email 중복 (EMPLOYEE_ALREADY_EXISTS) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee/{employeeId}/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 직원 팀 변경 (Manager Only)
         * @description `teamId`가 null이면 미배정 상태로 변경.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employeeId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeChangeTeamRequest"];
                };
            };
            responses: {
                /** @description 변경됨 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /**
                 * @description employeeId 또는 teamId 미존재.
                 *     코드: `EMPLOYEE_NOT_FOUND` 또는 `TEAM_NOT_FOUND`
                 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee/{employeeId}/retirement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 직원 퇴사 처리 (Manager Only)
         * @description `workEndDate`가 null이면 퇴사 취소(재직 상태로 복귀).
         *     퇴사한 달까지는 초과근무 리포트에 포함된다 — 그 달의 초과근무는 지급 대상.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employeeId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeRetirementRequest"];
                };
            };
            responses: {
                /** @description 변경됨 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 퇴사일이 입사일 이전 (INVALID_RETIREMENT_DATE) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description employeeId 미존재 (EMPLOYEE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee/{employeeId}/correction-approver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 정정 승인 담당자 지정 (Manager Only)
         * @description 근태 관리자(MANAGER)·상위 승인자(COMMUTE_APPROVER)의 정정 요청을 처리할 담당자를 지정한다.
         *     - MANAGER 대상 → COMMUTE_APPROVER 를 지정, COMMUTE_APPROVER 대상 → MANAGER 를 지정.
         *     - MEMBER 대상은 지정하지 않는다(모든 MANAGER 가 처리). 본인 지정 불가.
         *     - `approverId`가 null이면 지정 해제.
         *     - 대상 직원에게 PENDING 정정 요청이 있으면 변경할 수 없다 (취소 → 변경 → 재신청).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employeeId: components["parameters"]["EmployeeIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CorrectionApproverAssignRequest"];
                };
            };
            responses: {
                /** @description 변경됨. 응답 본문 없음. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description - INVALID_CORRECTION_APPROVER: 본인 지정, 역할 조합 불일치, MEMBER 대상 지정 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 대상 또는 담당자 직원 미존재 (EMPLOYEE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description 대상 직원에게 승인 대기 정정 요청이 있음 (PENDING_CORRECTION_EXISTS) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 월별 근무 시간 조회
         * @description 현재 로그인 직원의 특정 년/월 근무 시간을 일자별 + 합계로 반환.
         */
        get: {
            parameters: {
                query: {
                    /** @description ISO yyyy-MM */
                    yearMonth: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 월별 근무 시간 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkDurationPerDateResponse"];
                    };
                };
                /**
                 * @description 요청 파라미터 오류.
                 *     - MISSING_PARAMETER: yearMonth 누락
                 *     - INVALID_PARAMETER: yearMonth 형식 오류 (yyyy-MM 아님)
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        /**
         * 퇴근 등록 (일반 퇴근)
         * @description 현재 로그인 직원의 **가장 최근에 시작한 실제 근무**(연차 제외)를 서버 시각으로 종료한다.
         *     - 출근 시각부터 정확히 24시간까지 허용. 초과하면 정정 신청이 필요하다.
         *     - 최신 근무가 이미 종료됐으면 거부하며, 이전 미퇴근 기록을 대신 종료하지 않는다.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 기록됨. 응답 본문 없음. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /**
                 * @description 제약 위반.
                 *     - COMMUTE_NOT_STARTED: 실제 근무 기록이 하나도 없음
                 *     - INVALID_COMMUTE_RANGE: 퇴근 시간이 출근 시간보다 이름
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description 세션의 직원이 존재하지 않음 (EMPLOYEE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /**
                 * @description - COMMUTE_ALREADY_ENDED: 최신 근무가 이미 퇴근 처리됨(동시 퇴근 경합 포함)
                 *     - COMMUTE_END_WINDOW_EXPIRED: 출근 후 24시간 초과 — 정정 신청 필요
                 *     - CLOSING_PERIOD_LOCKED / REPORT_DELIVERY_UNCERTAIN: 출근 등록과 동일
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        /**
         * 출근 등록
         * @description 현재 로그인 직원의 출근 시각을 서버 시각으로 기록.
         *     과거 미퇴근 기록이 남아 있어도 새 근무일의 출근은 허용한다(해당 기록은 CORRECTION_REQUIRED 가 된다).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 기록됨. 응답 본문 없음. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                /** @description 세션의 직원이 존재하지 않음 (EMPLOYEE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /**
                 * @description 상태/중복 충돌.
                 *     - DUPLICATE_WORK: 같은 근무일에 이미 출근(또는 연차) 기록 존재
                 *     - CLOSING_PERIOD_LOCKED: 근무일이 마감된 보고서의 집계 입력 기간에 속함
                 *     - REPORT_DELIVERY_UNCERTAIN: 근무일이 수신 여부 미확인(DELIVERY_COMMITTED) 보고서의 입력 기간에 속함
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description 예상치 못한 데이터 제약 위반 (DATA_INTEGRITY_ERROR) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commute-corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 퇴근 시각 정정 신청 (본인 기록, 모든 역할)
         * @description 미퇴근 기록의 실제 종료 시각 등록, 또는 완료 기록의 종료 시각 변경(앞당김·늦춤)을 신청한다.
         *     신청은 원본 근태를 변경하지 않는다. 승인 시에만 종료 시각과 근무 분이 갱신된다.
         *
         *     `requestedWorkEndTime` 검증 (신청·승인 시점 모두):
         *     1. 출근 시각 이상 (동일 시각 허용 → 0분)
         *     2. 현재 시각 이하
         *     3. 후속 실제 근무가 있으면 그 출근 시각 이하
         *     4. 연차 기록이 아님
         *     일반 퇴근의 24시간 제한은 적용하지 않는다.
         *
         *     MANAGER·COMMUTE_APPROVER 는 지정 승인 담당자가 없어도 신청할 수 있다. 그 요청은 담당자가 없는 동안
         *     누구도 승인·반려할 수 없다(`assignedApprover` 생략, `actions.canReview` 항상 false).
         *     대기 중에는 담당자를 지정·변경할 수 없으므로 처리하려면 취소 → 담당자 지정 → 재신청 순서를 따른다.
         *     승인 대기 요청이므로 해당 기간의 월 마감도 막는다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CorrectionCreateRequest"];
                };
            };
            responses: {
                /** @description 신청됨 (status=PENDING) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CorrectionRequestResponse"];
                    };
                };
                /**
                 * @description - VALIDATION_ERROR: 필수값 누락, 사유 공백/500자 초과 (fieldErrorResults 에 필드명)
                 *     - INVALID_JSON: requestedWorkEndTime 형식 오류(오프셋 누락 포함)
                 *     - CORRECTION_TARGET_DAY_OFF: 연차 기록
                 *     - CORRECTION_END_BEFORE_START: 출근 시각 이전
                 *     - CORRECTION_END_IN_FUTURE: 현재 시각 이후
                 *     - CORRECTION_NO_CHANGE: 현재 종료 시각과 동일
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"] | components["schemas"]["ValidationErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description 본인 기록이 아님 (FORBIDDEN) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description 근태 기록 미존재 (COMMUTE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /**
                 * @description - CORRECTION_VERSION_CONFLICT: commuteVersion 이 현재 원본 버전과 다름 → 재조회 필요
                 *     - CORRECTION_ALREADY_PENDING: 이 기록에 승인 대기 요청이 이미 있음
                 *     - CORRECTION_OVERLAPS_NEXT_WORK: 후속 실제 근무의 출근 시각보다 늦음
                 *     - CLOSING_PERIOD_LOCKED: 마감된 보고서의 입력 기간
                 *     - REPORT_DELIVERY_UNCERTAIN: 수신 여부 미확인 보고서의 입력 기간
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commute-corrections/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정정 요청 이력 (모든 역할)
         * @description 본인이 신청한 요청 전체(모든 상태). 최근 신청 순.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 지정 시 해당 상태만 */
                    status?: components["parameters"]["CorrectionStatusQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 요청 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CorrectionRequestResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commute-corrections/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 처리 대상 정정 요청 목록 (MANAGER, COMMUTE_APPROVER)
         * @description 조회 범위:
         *     - MANAGER: MEMBER 가 신청한 요청 전체 + 본인이 지정 승인자인 요청
         *     - COMMUTE_APPROVER: 본인이 지정 승인자인 요청만
         *     본인이 신청한 요청은 포함하지 않는다. 최근 신청 순.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 지정 시 해당 상태만 */
                    status?: components["parameters"]["CorrectionStatusQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 요청 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CorrectionRequestResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commute-corrections/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 정정 요청 단건 조회
         * @description 신청자 본인 또는 review 조회 범위에 속하는 처리자만 조회 가능.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: components["parameters"]["CorrectionRequestIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 요청 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CorrectionRequestResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description CORRECTION_REQUEST_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commute-corrections/{requestId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 정정 요청 취소 (신청자 본인)
         * @description PENDING 요청만 취소할 수 있다. 취소된 요청도 이력으로 남는다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: components["parameters"]["CorrectionRequestIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 취소됨 (status=CANCELLED) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CorrectionRequestResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description 신청자 본인이 아님 (FORBIDDEN) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description CORRECTION_REQUEST_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description 이미 처리된 요청 (CORRECTION_ALREADY_PROCESSED) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commute-corrections/{requestId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 정정 요청 승인
         * @description 승인 권한: MEMBER 요청 → MANAGER, MANAGER 요청 → 지정된 COMMUTE_APPROVER,
         *     COMMUTE_APPROVER 요청 → 지정된 MANAGER. 자기 승인 금지.
         *     승인 트랜잭션에서 권한·지정 관계, PENDING 상태, 원본 버전, 연차 여부, 마감 범위,
         *     제안 시각과 후속 실제 근무를 다시 검사한다. 원본 갱신과 요청 처리는 한 트랜잭션이다.
         *     `CORRECTION_VERSION_CONFLICT`·`CORRECTION_OVERLAPS_NEXT_WORK` 는 요청을 REJECTED 로 바꾸지 않는다 —
         *     요청은 PENDING 으로 남고, 처리자가 재조회 후 반려하거나 신청자가 취소·재신청한다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: components["parameters"]["CorrectionRequestIdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CorrectionApproveRequest"];
                };
            };
            responses: {
                /** @description 승인됨 (status=APPROVED). 원본 근태의 종료 시각·근무 분이 갱신됨. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CorrectionRequestResponse"];
                    };
                };
                /**
                 * @description - VALIDATION_ERROR: comment 500자 초과
                 *     - CORRECTION_END_IN_FUTURE 등 시각 검증 실패(신청 이후 조건이 바뀐 경우)
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"] | components["schemas"]["ValidationErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /**
                 * @description - FORBIDDEN: 처리 권한 없음(역할 불일치·다른 담당자)
                 *     - CORRECTION_SELF_APPROVAL: 본인 요청
                 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description CORRECTION_REQUEST_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /**
                 * @description - CORRECTION_ALREADY_PROCESSED: PENDING 이 아님
                 *     - CORRECTION_VERSION_CONFLICT: 신청 이후 원본 기록이 바뀜
                 *     - CORRECTION_OVERLAPS_NEXT_WORK: 신청 이후 생긴 후속 출근과 겹침
                 *     - CORRECTION_APPROVER_NOT_ASSIGNED: MANAGER·COMMUTE_APPROVER 요청인데 지정 승인자가 없음(승인 불가)
                 *     - CLOSING_PERIOD_LOCKED / REPORT_DELIVERY_UNCERTAIN
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commute-corrections/{requestId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 정정 요청 반려
         * @description 승인과 같은 처리 권한. 반려 사유 필수. 원본 근태는 바뀌지 않는다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: components["parameters"]["CorrectionRequestIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CorrectionRejectRequest"];
                };
            };
            responses: {
                /** @description 반려됨 (status=REJECTED) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CorrectionRequestResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description FORBIDDEN 또는 CORRECTION_SELF_APPROVAL */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description CORRECTION_REQUEST_NOT_FOUND */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /**
                 * @description - CORRECTION_ALREADY_PROCESSED
                 *     - CORRECTION_APPROVER_NOT_ASSIGNED: 지정 승인자가 없는 MANAGER·COMMUTE_APPROVER 요청(반려도 불가)
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monthly-closings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 마감된 월 목록 (Manager Only)
         * @description 최근 월 순.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 마감 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonthlyClosingResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * 월 마감 (Manager Only)
         * @description 회사 달력(Asia/Seoul) 기준으로 끝난 과거 월만 마감한다. 집계 입력 기간
         *     (`rangeStart` = 월 1일이 속한 주의 월요일 ~ `rangeEnd` = 월말)에 미퇴근 또는 승인 대기 요청이
         *     있으면 거부한다. 마감은 DB에 먼저 커밋되고, 그 뒤 같은 요청 안에서 최종 보고서 발송을 시도한다.
         *     발송이 실패해도 마감은 유지된다(응답 `dispatch.status`=FAILED).
         *
         *     기능 도입 전에 이미 발송(SENT)된 월(`legacyDispatch`=true)은 `legacyResolution` 이 필수다.
         *     - NO_CORRECTION_NEEDED: 기존 발송 완료 월로 등록하고 잠근다. 재발송하지 않는다.
         *     - CORRECTED: 정정 완료 후 잠그고, 원본과 구분된 정정본(kind=CORRECTION)을 발송한다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MonthlyClosingCreateRequest"];
                };
            };
            responses: {
                /** @description 마감됨 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonthlyClosingCreateResponse"];
                    };
                };
                /**
                 * @description - VALIDATION_ERROR
                 *     - INVALID_PARAMETER / INVALID_JSON: yearMonth 형식 오류
                 *     - CLOSING_MONTH_NOT_ENDED: 진행 중이거나 미래 월
                 *     - LEGACY_RESOLUTION_NOT_APPLICABLE: 기존 발송 월이 아닌데 legacyResolution 지정
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"] | components["schemas"]["ValidationErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /**
                 * @description - MONTH_ALREADY_CLOSED
                 *     - CLOSING_HAS_UNRESOLVED: 입력 기간에 미퇴근/승인 대기 존재 (상세는 GET 상태 조회)
                 *     - LEGACY_RESOLUTION_REQUIRED: 기존 발송 월인데 legacyResolution 누락
                 *     - REPORT_DELIVERY_UNCERTAIN: 기존 발송이 DELIVERY_COMMITTED — 먼저 수신 확인 필요
                 *     - CLOSING_PREVIOUS_LEGACY_MONTH_PENDING: 입력 기간이 겹치는 이전 월이 미정리 기존 발송 월
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monthly-closings/{yearMonth}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 월 마감 상태 조회 (Manager Only)
         * @description 마감 가능 여부, 차단 사유, 미해결 목록, 발송 이력을 함께 돌려준다.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ISO yyyy-MM */
                    yearMonth: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 상태 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonthlyClosingStatusResponse"];
                    };
                };
                /** @description yearMonth 형식 오류 (INVALID_PARAMETER) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/annual-leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 잔여 연차 조회 (현재 로그인 직원) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 잔여 연차 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnnualLeaveGetRemainingResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 연차 신청 (현재 로그인 직원) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnnualLeaveEnrollRequest"];
                };
            };
            responses: {
                /** @description 등록된 연차 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnnualLeaveEnrollmentResponse"][];
                    };
                };
                /**
                 * @description 요청 검증 실패.
                 *     - VALIDATION_ERROR: 입력 형식 오류
                 *     - ANNUAL_LEAVE_CRITERIA_NOT_MET: 팀 연차 등록 기준 미충족
                 *     - ANNUAL_LEAVE_PAST_DATE: 과거 일자 신청
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description 세션의 직원이 존재하지 않음 (EMPLOYEE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /**
                 * @description 상태/중복 충돌.
                 *     - ANNUAL_LEAVE_DUPLICATE: 동일 일자 중복 신청
                 *     - EMPLOYEE_WITHOUT_TEAM: 팀 미배정 직원의 신청
                 *     - DUPLICATE_WORK: 신청 일자에 이미 출근 기록 존재
                 *     - CLOSING_PERIOD_LOCKED: 신청 일자가 마감된 보고서의 집계 입력 기간에 속함
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 월별 초과근무 계산 (Manager Only) */
        get: {
            parameters: {
                query: {
                    /** @description ISO yyyy-MM */
                    yearMonth: components["parameters"]["YearMonthQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 직원별 연장·휴일근로 분 (근로기준법 기준 — 일 8시간·주 40시간 초과, 휴일근로 별도 트랙) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OverTimeCalculateResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 공휴일 데이터 미가용 (HOLIDAY_DATA_UNAVAILABLE) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overtime/report/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 월별 초과근무 리포트 수동 발송 (Manager Only)
         * @description 매월 1~3일 배치·월 마감 직후 발송과 **완전히 같은** 멱등 경로를 즉시 실행한다.
         *     발송 종류(kind)는 마감 정보로 결정된다: 일반 마감 → ORIGINAL, 기존 발송 월 정정 마감 → CORRECTION.
         *     - 월이 마감되지 않았으면 대표에게 보내지 않고 `status`=FAILED, `lastFailureReason`=`MONTH_NOT_CLOSED: ...`.
         *     - 이미 SENT 또는 DELIVERY_COMMITTED 인 발송은 다시 보내지 않는다(강제 발송 플래그 없음).
         *     - 최초 시도에서 최종 Excel 을 생성·보관하고, 재시도는 보관 파일을 그대로 사용한다.
         *       파일 보관에 실패하면 발송하지 않는다.
         */
        post: {
            parameters: {
                query: {
                    /** @description ISO yyyy-MM */
                    yearMonth: components["parameters"]["YearMonthQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 실행 후 현재 발송 상태 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OverTimeReportDispatchResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overtime/report/dispatch/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 수신 여부 불명 발송의 운영자 확인 (Manager Only)
         * @description DELIVERY_COMMITTED(SMTP 호출 후 결과 미기록) 발송의 실제 수신 여부를 운영자가 확인해 기록한다.
         *     - DELIVERED → SENT 로 확정(재발송 없음).
         *     - NOT_DELIVERED → FAILED 로 전환해 다음 수동·예약 재시도가 보관 파일로 다시 보낼 수 있게 한다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DispatchConfirmationRequest"];
                };
            };
            responses: {
                /** @description 확인 후 발송 상태 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OverTimeReportDispatchResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 해당 월·종류의 발송 이력 없음 (DISPATCH_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description DELIVERY_COMMITTED 상태가 아님 (DISPATCH_NOT_UNCERTAIN) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overtime/report/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 월별 초과근무 Excel 참고용 다운로드 (Manager Only)
         * @description 현재 데이터로 매번 다시 집계한 **참고용** 파일이다. 마감 여부와 관계없이 확정본이 아니며,
         *     파일명과 시트 상단 문구로 참고용임을 표시한다. 승인 전 정정 신청 값은 섞지 않는다.
         *     확정본은 `/api/overtime/report/final-excel` 을 사용한다.
         */
        get: {
            parameters: {
                query: {
                    /** @description ISO yyyy-MM */
                    yearMonth: components["parameters"]["YearMonthQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /**
                 * @description xlsx 바이너리.
                 *     Content-Disposition: `attachment; filename*=UTF-8''YYYY년M월_초과근무보고서_참고용.xlsx`
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 공휴일 데이터 미가용 (HOLIDAY_DATA_UNAVAILABLE) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overtime/report/final-excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 월별 초과근무 확정본 다운로드 (Manager Only)
         * @description 발송에 사용한(또는 사용할) 보관 파일을 그대로 내려준다. 현재 데이터로 재생성하지 않는다.
         *     원본(ORIGINAL)과 기존 발송 월의 정정본(CORRECTION)은 별개 파일이다.
         */
        get: {
            parameters: {
                query: {
                    /** @description ISO yyyy-MM */
                    yearMonth: components["parameters"]["YearMonthQuery"];
                    /** @description 기본값 ORIGINAL */
                    kind?: components["schemas"]["ReportKind"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /**
                 * @description xlsx 바이너리.
                 *     Content-Disposition: ORIGINAL `YYYY년M월_초과근무보고서.xlsx`, CORRECTION `YYYY년M월_초과근무보고서_정정본.xlsx`
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    };
                };
                /** @description INVALID_PARAMETER / MISSING_PARAMETER */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 보관된 확정본 없음 (REPORT_FILE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResult: {
            /**
             * @description 에러 코드. 예시:
             *     - BAD_REQUEST, INVALID_JSON, INVALID_PARAMETER, MISSING_PARAMETER
             *     - UNAUTHORIZED, FORBIDDEN
             *     - TEAM_ALREADY_EXISTS, EMPLOYEE_ALREADY_EXISTS
             *     - TEAM_NOT_FOUND, EMPLOYEE_NOT_FOUND
             *     - DUPLICATE_WORK, DATA_INTEGRITY_ERROR
             *     - HOLIDAY_DATA_UNAVAILABLE
             *     - INTERNAL_SERVER_ERROR
             *     - CSRF_ORIGIN_REJECTED
             *     - 근태: COMMUTE_NOT_STARTED, COMMUTE_ALREADY_ENDED, COMMUTE_END_WINDOW_EXPIRED,
             *       INVALID_COMMUTE_RANGE, COMMUTE_NOT_FOUND, CLOSING_PERIOD_LOCKED, REPORT_DELIVERY_UNCERTAIN
             *     - 정정: CORRECTION_REQUEST_NOT_FOUND, CORRECTION_TARGET_DAY_OFF, CORRECTION_END_BEFORE_START,
             *       CORRECTION_END_IN_FUTURE, CORRECTION_NO_CHANGE, CORRECTION_OVERLAPS_NEXT_WORK,
             *       CORRECTION_ALREADY_PENDING, CORRECTION_VERSION_CONFLICT, CORRECTION_ALREADY_PROCESSED,
             *       CORRECTION_APPROVER_NOT_ASSIGNED, CORRECTION_SELF_APPROVAL
             *     - 담당자: INVALID_CORRECTION_APPROVER, PENDING_CORRECTION_EXISTS
             *     - 월 마감: CLOSING_MONTH_NOT_ENDED, MONTH_ALREADY_CLOSED, CLOSING_HAS_UNRESOLVED,
             *       LEGACY_RESOLUTION_REQUIRED, LEGACY_RESOLUTION_NOT_APPLICABLE, CLOSING_PREVIOUS_LEGACY_MONTH_PENDING
             *     - 발송: DISPATCH_NOT_FOUND, DISPATCH_NOT_UNCERTAIN, REPORT_FILE_NOT_FOUND
             */
            code: string;
            message: string;
        };
        FieldErrorResult: {
            field: string;
            message: string;
        };
        ValidationErrorResult: {
            /** @example VALIDATION_ERROR */
            code: string;
            /** @example 입력값이 올바르지 않습니다 */
            message: string;
            fieldErrorResults: components["schemas"]["FieldErrorResult"][];
        };
        /**
         * @description MANAGER = 근태 관리자(직원·팀·초과근무·월 마감 등 관리자 기능 + MEMBER 정정 승인),
         *     MEMBER = 일반 직원,
         *     COMMUTE_APPROVER = 상위 승인자. 지정된 대상(MANAGER)의 정정 요청 조회·승인·반려만 가능하며
         *     관리자 기능 권한은 없다. 모든 역할은 본인 출퇴근·근태 조회·정정 신청을 사용한다.
         * @enum {string}
         */
        Role: "MANAGER" | "MEMBER" | "COMMUTE_APPROVER";
        EmployeeRef: {
            /** Format: int64 */
            employeeId: number;
            name: string;
            employeeCode: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        CurrentUserResponse: {
            /** Format: int64 */
            employeeId: number;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: int64 */
            teamId?: number | null;
            teamName?: string | null;
            /**
             * @description 본인 정정 요청의 지정 승인자. MEMBER 는 항상 없음(모든 MANAGER 가 처리).
             *     MANAGER·COMMUTE_APPROVER 인데 없으면 신청은 되지만 그 요청은 승인·반려할 수 없다
             *     (처리 시 409 CORRECTION_APPROVER_NOT_ASSIGNED). 담당자 지정 후 재신청해야 처리된다.
             */
            correctionApprover?: components["schemas"]["EmployeeRef"] | null;
        };
        TeamRegisterRequest: {
            teamName: string;
            /** @description 옵셔널. 빈 문자열은 null로 정규화됨. */
            managerName?: string | null;
            /**
             * Format: int32
             * @description 팀 연차 등록 기준. null 또는 생략 시 0으로 처리됨.
             * @default 0
             */
            annualLeaveCriteria: number | null;
        };
        TeamRegisterResponse: {
            /** Format: int64 */
            teamId: number;
        };
        TeamFindResponse: {
            /** Format: int64 */
            teamId: number;
            name: string;
            managerName?: string | null;
            /** Format: int32 */
            annualLeaveCriteria: number;
            /**
             * Format: int64
             * @description employee.team_id COUNT 파생값.
             */
            memberCount: number;
        };
        EmployeeSaveRequest: {
            /** @description 직원 이름 */
            name: string;
            role: components["schemas"]["Role"];
            /**
             * Format: date
             * @description 과거 날짜
             */
            birthday: string;
            /**
             * Format: date
             * @description 오늘 또는 과거 날짜
             */
            workStartDate: string;
            /** @description 사번 (대문자/숫자 6-10자) */
            employeeCode: string;
            /** Format: email */
            email: string;
            /** @description 평문. 서버에서 BCrypt로 인코딩. */
            password: string;
            /**
             * Format: int64
             * @description 옵셔널. 없으면 미배정.
             */
            teamId?: number | null;
            /**
             * @description 직원의 기본 시간대 (IANA ZoneId). 옵셔널 — null이거나 빈 문자열이면 서버 기본값 `Asia/Seoul` 적용.
             *     유효하지 않은 ZoneId면 400 `VALIDATION_ERROR`.
             *     출퇴근 등록 시 이 값을 기준으로 `workDate`가 계산되며, 각 출근 레코드에 snapshot으로 저장된다.
             * @example Asia/Seoul
             */
            timezone?: string | null;
        };
        EmployeeRegisterResponse: {
            /** Format: int64 */
            employeeId: number;
        };
        EmployeeFindResponse: {
            /** Format: int64 */
            employeeId: number;
            /** Format: int64 */
            teamId?: number | null;
            teamName?: string | null;
            name: string;
            employeeCode: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: date */
            birthday: string;
            /** Format: date */
            workStartDate: string;
            /**
             * Format: date
             * @description 퇴사일. null = 재직 중.
             */
            workEndDate?: string | null;
            /**
             * @description IANA ZoneId — 직원의 기본 시간대.
             * @example Asia/Seoul
             */
            timezone: string;
            /** @description 정정 승인 담당자(MANAGER·COMMUTE_APPROVER 대상만 지정됨). */
            correctionApprover?: components["schemas"]["EmployeeRef"] | null;
        };
        EmployeeChangeTeamRequest: {
            /**
             * Format: int64
             * @description null이면 미배정 상태로 변경.
             */
            teamId?: number | null;
        };
        EmployeeRetirementRequest: {
            /**
             * Format: date
             * @description 퇴사일. null이면 퇴사 취소. 입사일 이전이면 400.
             *     퇴사일 지정(계정 비활성화)은 그 직원이 신청자이거나 지정 승인자인 PENDING 정정 요청이 있으면
             *     409 PENDING_CORRECTION_EXISTS 로 거부된다.
             */
            workEndDate?: string | null;
        };
        CorrectionApproverAssignRequest: {
            /**
             * Format: int64
             * @description 지정할 승인 담당자 직원 ID. null이면 지정 해제.
             */
            approverId?: number | null;
        };
        AnnualLeaveEnrollRequest: {
            /** @description 미래 날짜 목록. */
            wantedDates: string[];
        };
        AnnualLeaveEnrollmentResponse: {
            /** Format: int64 */
            annualLeaveId: number;
            /** Format: date */
            enrolledDate: string;
        };
        AnnualLeave: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            employeeId: number;
            /** Format: date */
            wantedDate: string;
        };
        AnnualLeaveGetRemainingResponse: {
            /** Format: int64 */
            employeeId: number;
            remainingLeaves: components["schemas"]["AnnualLeave"][];
        };
        /**
         * @description 서버가 파생 계산하는 근태 상태(저장 컬럼 아님). 정정 요청 상태와는 별개다.
         *     - DAY_OFF = 연차
         *     - COMPLETED = 종료 시각 있음 (승인 대기 정정이 있어도 COMPLETED)
         *     - CORRECTION_REQUIRED = 미퇴근이면서 (출근 후 24시간 초과 또는 후속 실제 근무 존재)
         *       → 일반 퇴근 불가, 정정 신청으로만 해결. 신청 제출 여부를 뜻하지 않는다.
         *     - IN_PROGRESS = 그 외 미퇴근 (일반 퇴근 가능 — 날짜가 바뀐 야간근무 포함)
         * @enum {string}
         */
        CommuteStatus: "COMPLETED" | "IN_PROGRESS" | "CORRECTION_REQUIRED" | "DAY_OFF";
        /**
         * @description MONTH_CLOSED = 마감된 보고서의 집계 입력 기간(전월 말 참조 기간 포함),
         *     DELIVERY_UNCERTAIN = 수신 여부 미확인 보고서의 입력 기간(운영자 확인 전 임시 차단)
         * @enum {string}
         */
        CommuteLockReason: "MONTH_CLOSED" | "DELIVERY_UNCERTAIN";
        CommuteDetail: {
            /**
             * Format: int64
             * @description 근태 기록 ID (정정 신청 대상)
             */
            commuteHistoryId: number;
            /**
             * Format: int64
             * @description 원본 버전. 정정 신청 시 `commuteVersion` 으로 그대로 보낸다. 이 기록이 바뀔 때마다 증가한다.
             */
            version: number;
            /**
             * Format: date
             * @description 근무일 (기록 당시 workZone 기준 확정값)
             */
            date: string;
            /**
             * @description 기록 당시 직원 시간대(IANA). 표시·입력 변환에 사용
             * @example Asia/Seoul
             */
            workZone: string;
            /**
             * Format: date-time
             * @description 출근 시각. 기록의 workZone 오프셋으로 내려간다 — 표시는 이 오프셋
             *     기준으로 하고 브라우저 timezone 으로 재해석하지 않는다.
             *     연차 기록은 출퇴근 시각이 자정으로 합성된 값이므로 내려가지 않는다.
             * @example 2026-08-19T09:03:12+09:00
             */
            workStartTime?: string | null;
            /**
             * Format: date-time
             * @description 퇴근 시각. 미퇴근이거나 연차이면 내려가지 않는다.
             *     날짜 부분이 date 와 다르면 자정을 넘긴 근무다.
             * @example 2026-08-19T18:58:41+09:00
             */
            workEndTime?: string | null;
            /**
             * Format: int64
             * @description 저장된 근무 분(분 미만 절삭). 미퇴근·연차는 0 — 미퇴근의 0은 "근무하지 않음"의 확정값이 아니다.
             */
            workingMinutes: number;
            usingDayOff: boolean;
            status: components["schemas"]["CommuteStatus"];
            /**
             * Format: int64
             * @description 이 기록의 승인 대기(PENDING) 정정 요청 ID. 없으면 생략.
             */
            pendingCorrectionRequestId?: number | null;
            /** @description 값이 있으면 이 기록은 정정·퇴근 등 모든 쓰기가 막혀 있다. */
            lockReason?: components["schemas"]["CommuteLockReason"] | null;
        };
        /**
         * @description 지금 `PUT /api/commute`(일반 퇴근)를 부르면 종료되는 기록. 가장 최근에 시작한 실제 근무(연차 제외)가
         *     미퇴근이고 출근 후 24시간 이내일 때만 내려간다. 조회 월과 무관하게 같은 값이다 —
         *     9/30 22:00 에 시작한 야간근무는 10월을 조회해도 이 필드로 식별된다(details 에는 없다).
         */
        RegularEndTarget: {
            /** Format: int64 */
            commuteHistoryId: number;
            /** Format: int64 */
            version: number;
            /**
             * Format: date
             * @description 근무일 — 조회 월과 다를 수 있다
             */
            workDate: string;
            /** @example Asia/Seoul */
            workZone: string;
            /**
             * Format: date-time
             * @description workZone 오프셋
             */
            workStartTime: string;
            /**
             * Format: date-time
             * @description 일반 퇴근 마감 시각(출근 + 정확히 24시간, workZone 오프셋). 이후에는 정정 신청 대상이다.
             */
            endableUntil: string;
            /** @description 값이 있으면 퇴근해도 보호 기간 오류(409)가 난다. 드문 경우(다른 시간대 근무일이 마감 월)다. */
            lockReason?: components["schemas"]["CommuteLockReason"] | null;
        };
        WorkDurationPerDateResponse: {
            details: components["schemas"]["CommuteDetail"][];
            /** Format: int64 */
            sumWorkingMinutes: number;
            /**
             * @description 일반 퇴근 대상. 없으면 생략 — 퇴근 버튼을 비활성화한다(최신 근무가 이미 끝났거나, 24시간이 지났거나,
             *     실제 근무 기록이 없음). details 의 같은 commuteHistoryId 행이 퇴근 대상이다.
             */
            regularEndTarget?: components["schemas"]["RegularEndTarget"] | null;
        };
        /**
         * @description 정정 요청 상태. PENDING 에서 한 번만 전이하며 종착 상태는 변경되지 않는다.
         * @enum {string}
         */
        CorrectionStatus: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED";
        CorrectionCreateRequest: {
            /** Format: int64 */
            commuteHistoryId: number;
            /**
             * Format: int64
             * @description 화면이 본 CommuteDetail.version. 다르면 409 CORRECTION_VERSION_CONFLICT.
             */
            commuteVersion: number;
            /**
             * Format: date-time
             * @description 실제 종료 시각. **오프셋 필수**(RFC 3339). 서버는 UTC Instant 로 변환해 비교·저장하며
             *     초 미만은 버린다(초 단위 저장). 기록의 workZone 현지 시각을 오프셋으로 바꾸는 일은 클라이언트가 한다 —
             *     DST 로 존재하지 않는 현지 시각은 입력 단계에서 막고, 중복되는 현지 시각은 사용자가 오프셋을 선택하게 한다.
             * @example 2026-09-02T19:30:00+09:00
             */
            requestedWorkEndTime: string;
            /** @description 정정 사유(필수, 공백만은 불가) */
            reason: string;
        };
        CorrectionApproveRequest: {
            /** @description 승인 의견(선택) */
            comment?: string | null;
        };
        CorrectionRejectRequest: {
            /** @description 반려 사유(필수, 공백만은 불가) */
            reason: string;
        };
        /** @description 현재 사용자 기준으로 지금 가능한 동작. 서버가 다시 검사하므로 표시용이다. */
        CorrectionActions: {
            /** @description 신청자 본인 + PENDING */
            canCancel: boolean;
            /** @description 승인·반려 권한 + PENDING */
            canReview: boolean;
        };
        CorrectionRequestResponse: {
            /** Format: int64 */
            requestId: number;
            status: components["schemas"]["CorrectionStatus"];
            /** Format: int64 */
            commuteHistoryId: number;
            /**
             * Format: int64
             * @description 신청 당시 원본 버전
             */
            commuteVersion: number;
            requester: components["schemas"]["EmployeeRef"];
            requesterRole: components["schemas"]["Role"];
            /** @description 신청 당시 지정 승인자. MEMBER 요청은 없음(모든 MANAGER). */
            assignedApprover?: components["schemas"]["EmployeeRef"] | null;
            /**
             * Format: date
             * @description 기록의 근무일(신청 당시 스냅샷)
             */
            workDate: string;
            /** @description 기록 당시 시간대. 아래 시각은 모두 이 오프셋으로 내려간다 */
            workZone: string;
            /** Format: date-time */
            workStartTime: string;
            /**
             * Format: date-time
             * @description 신청 당시 종료 시각. 미퇴근 기록이면 생략. 승인은 원본 버전이 같을 때만 적용되므로 승인 직전 값과 같다.
             */
            previousWorkEndTime?: string | null;
            /**
             * Format: int64
             * @description 신청 당시 저장 근무 분
             */
            previousWorkingMinutes: number;
            /** Format: date-time */
            requestedWorkEndTime: string;
            /**
             * Format: int64
             * @description 승인 시 저장될 근무 분(분 미만 절삭)
             */
            requestedWorkingMinutes: number;
            reason: string;
            /**
             * Format: date-time
             * @description UTC
             */
            requestedAt: string;
            /** @description 승인·반려자 또는 취소한 신청자. PENDING 이면 생략. */
            processedBy?: components["schemas"]["EmployeeRef"] | null;
            /**
             * Format: date-time
             * @description UTC
             */
            processedAt?: string | null;
            /** @description 승인 의견(APPROVED, 선택) 또는 반려 사유(REJECTED, 필수) */
            reviewComment?: string | null;
            actions: components["schemas"]["CorrectionActions"];
        };
        /**
         * @description MANUAL = 신규 기능의 수동 월 마감(마감 후 원본 발송),
         *     LEGACY_CONFIRMED = 기능 도입 전 발송 월을 정정 없이 기존 발송 완료 월로 등록,
         *     LEGACY_CORRECTED = 기능 도입 전 발송 월을 정정 후 잠금(정정본 별도 발송)
         * @enum {string}
         */
        MonthlyClosingType: "MANUAL" | "LEGACY_CONFIRMED" | "LEGACY_CORRECTED";
        /** @enum {string} */
        LegacyResolution: "NO_CORRECTION_NEEDED" | "CORRECTED";
        MonthlyClosingCreateRequest: {
            /**
             * @description ISO yyyy-MM
             * @example 2026-09
             */
            yearMonth: string;
            /** @description 기존 발송 월(legacyDispatch=true)에만 필수. 그 외에는 생략. */
            legacyResolution?: components["schemas"]["LegacyResolution"] | null;
            /** @description 운영 메모. 기존 발송 월은 필수(확인한 사실, 원본 파일 확보 여부 등). */
            note?: string | null;
        };
        MonthlyClosingResponse: {
            /** @example 2026-09 */
            yearMonth: string;
            type: components["schemas"]["MonthlyClosingType"];
            /**
             * Format: date
             * @description 보호(집계 입력) 기간 시작 — 월 1일이 속한 주의 월요일
             */
            rangeStart: string;
            /**
             * Format: date
             * @description 보호 기간 끝 — 월말
             */
            rangeEnd: string;
            closedBy: components["schemas"]["EmployeeRef"];
            /**
             * Format: date-time
             * @description UTC
             */
            closedAt: string;
            note?: string | null;
        };
        /** @enum {string} */
        ClosingBlocker: "MONTH_NOT_ENDED" | "ALREADY_CLOSED" | "UNCLOSED_COMMUTES" | "PENDING_CORRECTIONS" | "DELIVERY_UNCERTAIN" | "PREVIOUS_LEGACY_MONTH_PENDING";
        UnresolvedCommute: {
            /** Format: int64 */
            commuteHistoryId: number;
            employee: components["schemas"]["EmployeeRef"];
            /** Format: date */
            workDate: string;
        };
        PendingCorrectionSummary: {
            /** Format: int64 */
            requestId: number;
            /** Format: int64 */
            commuteHistoryId: number;
            requester: components["schemas"]["EmployeeRef"];
            /** Format: date */
            workDate: string;
        };
        MonthlyClosingStatusResponse: {
            /** @example 2026-09 */
            yearMonth: string;
            /** Format: date */
            rangeStart: string;
            /** Format: date */
            rangeEnd: string;
            /** @description blockers 가 비었는가 */
            closable: boolean;
            /** @description 마감 정보. 미마감이면 생략. */
            closing?: components["schemas"]["MonthlyClosingResponse"] | null;
            /** @description 마감 없이 원본 보고서가 이미 발송(SENT)된 기능 도입 전 월 — 마감 시 legacyResolution 필수 */
            legacyDispatch: boolean;
            blockers: components["schemas"]["ClosingBlocker"][];
            /** @description 입력 기간의 미퇴근 기록 */
            unclosedCommutes: components["schemas"]["UnresolvedCommute"][];
            /** @description 입력 기간 기록에 대한 승인 대기 요청 */
            pendingCorrections: components["schemas"]["PendingCorrectionSummary"][];
            /** @description 이 월의 발송 이력(ORIGINAL, CORRECTION) */
            dispatches: components["schemas"]["OverTimeReportDispatchResponse"][];
        };
        MonthlyClosingCreateResponse: {
            closing: components["schemas"]["MonthlyClosingResponse"];
            /** @description 마감 커밋 후 시도한 발송 결과. LEGACY_CONFIRMED 는 발송하지 않으므로 생략. */
            dispatch?: components["schemas"]["OverTimeReportDispatchResponse"] | null;
        };
        /**
         * @description ORIGINAL = 해당 월 최초 보고서, CORRECTION = 기능 도입 전 발송 월의 정정본(원본과 별도 식별·파일·발송 이력)
         * @enum {string}
         */
        ReportKind: "ORIGINAL" | "CORRECTION";
        /**
         * @description IN_PROGRESS = 다른 실행이 선점 중,
         *     DELIVERY_COMMITTED = SMTP 호출을 시작했으나 결과 미기록 — 수신 여부 불명, 자동 재발송 안 함(운영자 확인 필요),
         *     SENT = 대표에게 발송 완료(종착),
         *     FAILED = 시도했으나 실패 — 재시도 창(1~3일) 안이면 다음 시도가 다시 집어간다
         * @enum {string}
         */
        DispatchStatus: "IN_PROGRESS" | "DELIVERY_COMMITTED" | "SENT" | "FAILED";
        /** @enum {string} */
        DispatchConfirmationOutcome: "DELIVERED" | "NOT_DELIVERED";
        DispatchConfirmationRequest: {
            /** @example 2026-08 */
            yearMonth: string;
            kind: components["schemas"]["ReportKind"];
            outcome: components["schemas"]["DispatchConfirmationOutcome"];
            /** @description 확인 근거(필수) */
            note: string;
        };
        OverTimeReportDispatchResponse: {
            /**
             * @description ISO yyyy-MM
             * @example 2026-07
             */
            yearMonth: string;
            kind: components["schemas"]["ReportKind"];
            status: components["schemas"]["DispatchStatus"];
            /**
             * Format: int32
             * @description 결과가 기록된 시도 횟수
             */
            attemptCount: number;
            /**
             * Format: date-time
             * @description UTC
             */
            lastAttemptedAt: string;
            /**
             * Format: date-time
             * @description 발송 완료 시각(SENT 일 때만)
             */
            sentAt?: string | null;
            /**
             * @description "분류: 상세" 형식. 분류는 MONTH_NOT_CLOSED / UNCLOSED_COMMUTES / HOLIDAY_DATA_UNAVAILABLE /
             *     MAIL_SEND_FAILED / UNEXPECTED. 파일 보관 실패는 UNEXPECTED 로 기록되며 발송하지 않는다.
             *     MONTH_NOT_CLOSED 는 장애가 아니라 "월 마감 전이라 보류" 상태다.
             */
            lastFailureReason?: string | null;
            /** @description 보관된 확정본 파일이 있는가(final-excel 다운로드 가능) */
            finalFileAvailable: boolean;
            /** @description DELIVERY_COMMITTED 를 운영자가 확인한 경우의 확인자 */
            deliveryConfirmedBy?: components["schemas"]["EmployeeRef"] | null;
            /** Format: date-time */
            deliveryConfirmedAt?: string | null;
            deliveryConfirmationNote?: string | null;
        };
        OverTimeCalculateResponse: {
            /** Format: int64 */
            id: number;
            employeeCode: string;
            name: string;
            teamName: string | null;
            /**
             * Format: int64
             * @description 연장근로 분 — 1일 8시간 초과분 + 1주(월~일) 40시간 초과 잔여분, 가산 1.5배
             */
            overTimeMinutes: number;
            /**
             * Format: int64
             * @description 휴일근로(일요일·공휴일) 중 1일 8시간 이내 분, 가산 1.5배
             */
            holidayWithin8HoursMinutes: number;
            /**
             * Format: int64
             * @description 휴일근로 중 1일 8시간 초과 분, 가산 2.0배
             */
            holidayExceeding8HoursMinutes: number;
        };
    };
    responses: {
        /** @description 잘못된 요청 (BAD_REQUEST / INVALID_JSON 등) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResult"];
            };
        };
        /** @description 입력값 검증 실패 (VALIDATION_ERROR) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorResult"];
            };
        };
        /** @description 비로그인 (UNAUTHORIZED) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResult"];
            };
        };
        /** @description 권한 부족 (FORBIDDEN) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResult"];
            };
        };
    };
    parameters: {
        EmployeeIdPath: number;
        CorrectionRequestIdPath: number;
        /** @description 지정 시 해당 상태만 */
        CorrectionStatusQuery: components["schemas"]["CorrectionStatus"];
        /** @description ISO yyyy-MM */
        YearMonthQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
