/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 성공 시 새 HTTP 세션을 생성하고 `currentEmployeeId`, `currentRole`을 저장한다.
         *     기존 세션은 무효화된다(session fixation 방어).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 로그인 성공. 응답 본문 없음. Set-Cookie로 JSESSIONID 발급. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                /** @description 이메일 미존재 또는 비밀번호 불일치 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 로그인한 사용자 조회
         * @description 세션에 저장된 `currentEmployeeId`로 현재 사용자를 조회한다.
         *     SPA 부팅 시 로그인 상태 복원 및 역할 기반 화면 분기에 사용한다.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 현재 세션을 무효화한다. 세션이 없어도 200으로 처리한다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 로그아웃 처리됨. 응답 본문 없음. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 전체 조회
         * @description `memberCount`는 저장된 카운터가 아니라 `employee.team_id`의 COUNT 결과를 응답 시점에 합성한 값이다.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 팀 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamFindResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 팀 등록 (Manager Only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamRegisterRequest"];
                };
            };
            responses: {
                /** @description 등록 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamRegisterResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 동일 이름의 팀이 이미 존재 (TEAM_ALREADY_EXISTS) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 직원 전체 조회 (Manager Only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 직원 목록. 미배정 직원은 `teamId`/`teamName`이 null. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeFindResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * 직원 등록 (Manager Only)
         * @description `teamId`는 옵셔널. 없으면 미배정 직원으로 저장.
         *     `password`는 BCrypt로 인코딩되어 저장된다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeSaveRequest"];
                };
            };
            responses: {
                /** @description 등록 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeRegisterResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description teamId가 존재하지 않음 (TEAM_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description employeeCode 또는 email 중복 (EMPLOYEE_ALREADY_EXISTS) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employee/{employeeId}/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 직원 팀 변경 (Manager Only)
         * @description `teamId`가 null이면 미배정 상태로 변경.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employeeId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmployeeChangeTeamRequest"];
                };
            };
            responses: {
                /** @description 변경됨 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /**
                 * @description employeeId 또는 teamId 미존재.
                 *     코드: `EMPLOYEE_NOT_FOUND` 또는 `TEAM_NOT_FOUND`
                 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 월별 근무 시간 조회
         * @description 현재 로그인 직원의 특정 년/월 근무 시간을 일자별 + 합계로 반환.
         */
        get: {
            parameters: {
                query: {
                    /** @description ISO yyyy-MM */
                    yearMonth: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 월별 근무 시간 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkDurationPerDateResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        /**
         * 퇴근 등록
         * @description 현재 로그인 직원의 퇴근 시각을 서버 시각으로 기록.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 기록됨. 응답 본문 없음. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /**
                 * @description 제약 위반.
                 *     - COMMUTE_NOT_STARTED: 진행 중인 출근 기록이 없음
                 *     - INVALID_COMMUTE_RANGE: 퇴근 시간이 출근 시간보다 이름
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description 세션의 직원이 존재하지 않음 (EMPLOYEE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description 이미 퇴근 처리됨 (COMMUTE_ALREADY_ENDED) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        /**
         * 출근 등록
         * @description 현재 로그인 직원의 출근 시각을 서버 시각으로 기록.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 기록됨. 응답 본문 없음. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                /** @description 세션의 직원이 존재하지 않음 (EMPLOYEE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /**
                 * @description 상태/중복 충돌.
                 *     - PREVIOUS_COMMUTE_NOT_ENDED: 다른 날 근무가 종료되지 않음
                 *     - DUPLICATE_WORK: 같은 날 이미 출근 기록 존재
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /** @description 예상치 못한 데이터 제약 위반 (DATA_INTEGRITY_ERROR) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/annual-leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 잔여 연차 조회 (현재 로그인 직원) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 잔여 연차 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnnualLeaveGetRemainingResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 연차 신청 (현재 로그인 직원) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnnualLeaveEnrollRequest"];
                };
            };
            responses: {
                /** @description 등록된 연차 목록 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnnualLeaveEnrollmentResponse"][];
                    };
                };
                /**
                 * @description 요청 검증 실패.
                 *     - VALIDATION_ERROR: 입력 형식 오류
                 *     - ANNUAL_LEAVE_CRITERIA_NOT_MET: 팀 연차 등록 기준 미충족
                 *     - ANNUAL_LEAVE_PAST_DATE: 과거 일자 신청
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description 세션의 직원이 존재하지 않음 (EMPLOYEE_NOT_FOUND) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
                /**
                 * @description 상태/중복 충돌.
                 *     - ANNUAL_LEAVE_DUPLICATE: 동일 일자 중복 신청
                 *     - EMPLOYEE_WITHOUT_TEAM: 팀 미배정 직원의 신청
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 월별 초과근무 계산 (Manager Only) */
        get: {
            parameters: {
                query: {
                    /** @description ISO yyyy-MM */
                    yearMonth: components["parameters"]["YearMonthQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 직원별 초과근무 분 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OverTimeCalculateResponse"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 공휴일 데이터 미가용 (HOLIDAY_DATA_UNAVAILABLE) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overtime/report/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 월별 초과근무 Excel 리포트 다운로드 (Manager Only) */
        get: {
            parameters: {
                query: {
                    /** @description ISO yyyy-MM */
                    yearMonth: components["parameters"]["YearMonthQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /**
                 * @description xlsx 바이너리.
                 *     Content-Disposition: `attachment; filename*=UTF-8''YYYY년M월_초과근무보고서.xlsx`
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 공휴일 데이터 미가용 (HOLIDAY_DATA_UNAVAILABLE) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResult: {
            /**
             * @description 에러 코드. 예시:
             *     - BAD_REQUEST, INVALID_JSON, INVALID_PARAMETER, MISSING_PARAMETER
             *     - UNAUTHORIZED, FORBIDDEN
             *     - TEAM_ALREADY_EXISTS, EMPLOYEE_ALREADY_EXISTS
             *     - TEAM_NOT_FOUND, EMPLOYEE_NOT_FOUND
             *     - DUPLICATE_WORK, DATA_INTEGRITY_ERROR
             *     - HOLIDAY_DATA_UNAVAILABLE
             *     - INTERNAL_SERVER_ERROR
             */
            code: string;
            message: string;
        };
        FieldErrorResult: {
            field: string;
            message: string;
        };
        ValidationErrorResult: {
            /** @example VALIDATION_ERROR */
            code: string;
            /** @example 입력값이 올바르지 않습니다 */
            message: string;
            fieldErrorResults: components["schemas"]["FieldErrorResult"][];
        };
        /** @enum {string} */
        Role: "MANAGER" | "MEMBER";
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        CurrentUserResponse: {
            /** Format: int64 */
            employeeId: number;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: int64 */
            teamId?: number | null;
            teamName?: string | null;
        };
        TeamRegisterRequest: {
            teamName: string;
            /** @description 옵셔널. 빈 문자열은 null로 정규화됨. */
            managerName?: string | null;
            /**
             * Format: int32
             * @description 팀 연차 등록 기준. null 또는 생략 시 0으로 처리됨.
             * @default 0
             */
            annualLeaveCriteria: number | null;
        };
        TeamRegisterResponse: {
            /** Format: int64 */
            teamId: number;
        };
        TeamFindResponse: {
            /** Format: int64 */
            teamId: number;
            name: string;
            managerName?: string | null;
            /** Format: int32 */
            annualLeaveCriteria: number;
            /**
             * Format: int64
             * @description employee.team_id COUNT 파생값.
             */
            memberCount: number;
        };
        EmployeeSaveRequest: {
            /** @description 직원 이름 */
            name: string;
            role: components["schemas"]["Role"];
            /**
             * Format: date
             * @description 과거 날짜
             */
            birthday: string;
            /**
             * Format: date
             * @description 오늘 또는 과거 날짜
             */
            workStartDate: string;
            /** @description 사번 (대문자/숫자 6-10자) */
            employeeCode: string;
            /** Format: email */
            email: string;
            /** @description 평문. 서버에서 BCrypt로 인코딩. */
            password: string;
            /**
             * Format: int64
             * @description 옵셔널. 없으면 미배정.
             */
            teamId?: number | null;
            /**
             * @description 직원의 기본 시간대 (IANA ZoneId). 옵셔널 — null이거나 빈 문자열이면 서버 기본값 `Asia/Seoul` 적용.
             *     출퇴근 등록 시 이 값을 기준으로 `workDate`가 계산되며, 각 출근 레코드에 snapshot으로 저장된다.
             * @example Asia/Seoul
             */
            timezone?: string | null;
        };
        EmployeeRegisterResponse: {
            /** Format: int64 */
            employeeId: number;
        };
        EmployeeFindResponse: {
            /** Format: int64 */
            employeeId: number;
            /** Format: int64 */
            teamId?: number | null;
            teamName?: string | null;
            name: string;
            role: components["schemas"]["Role"];
            /** Format: date */
            birthday: string;
            /** Format: date */
            workStartDate: string;
            /**
             * @description IANA ZoneId — 직원의 기본 시간대.
             * @example Asia/Seoul
             */
            timezone: string;
        };
        EmployeeChangeTeamRequest: {
            /**
             * Format: int64
             * @description null이면 미배정 상태로 변경.
             */
            teamId?: number | null;
        };
        AnnualLeaveEnrollRequest: {
            /** @description 미래 날짜 목록. */
            wantedDates: string[];
        };
        AnnualLeaveEnrollmentResponse: {
            /** Format: int64 */
            annualLeaveId: number;
            /** Format: date */
            enrolledDate: string;
        };
        AnnualLeave: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            employeeId: number;
            /** Format: date */
            wantedDate: string;
        };
        AnnualLeaveGetRemainingResponse: {
            /** Format: int64 */
            employeeId: number;
            remainingLeaves: components["schemas"]["AnnualLeave"][];
        };
        CommuteDetail: {
            /** Format: date */
            date: string;
            usingDayOff: boolean;
        };
        WorkDurationPerDateResponse: {
            details: components["schemas"]["CommuteDetail"][];
            /** Format: int64 */
            sumWorkingMinutes: number;
        };
        OverTimeCalculateResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            teamName: string | null;
            /** Format: int64 */
            overTimeMinutes: number;
        };
    };
    responses: {
        /** @description 잘못된 요청 (BAD_REQUEST / INVALID_JSON 등) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResult"];
            };
        };
        /** @description 입력값 검증 실패 (VALIDATION_ERROR) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorResult"];
            };
        };
        /** @description 비로그인 (UNAUTHORIZED) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResult"];
            };
        };
        /** @description 권한 부족 (FORBIDDEN) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResult"];
            };
        };
    };
    parameters: {
        /** @description ISO yyyy-MM */
        YearMonthQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
